const PASSWORD_DEMO="cristian123";function login(){const p=document.getElementById("password").value;if(p===PASSWORD_DEMO){document.getElementById("loginBox").style.display="none";document.getElementById("portal").style.display="block";cargarCitas();}else document.getElementById("loginMsg").textContent="Contraseña incorrecta."}function mostrarTab(t){document.getElementById("tab-citas").style.display=t==="citas"?"block":"none";document.getElementById("tab-clientes").style.display=t==="clientes"?"block":"none";document.getElementById("tab-vehiculos").style.display=t==="vehiculos"?"block":"none";if(t==="clientes")cargarClientes();if(t==="vehiculos")cargarVehiculos();}
async function cargarCitas(){const cont=document.getElementById("listaCitas");if(SUPABASE_URL.includes("PEGA_AQUI")){cont.innerHTML="<p>Falta conectar Supabase.</p>";return;}const{data,error}=await supabaseClient.from("citas").select("*").order("fecha",{ascending:true}).order("hora",{ascending:true});if(error){cont.innerHTML="<p>Error al cargar citas.</p>";console.error(error);return;}

const pendientes = data.filter(c => c.estado_cita === "Pendiente").length;
const hoy = new Date().toISOString().slice(0,10);
const citasHoy = data.filter(c => c.fecha === hoy).length;
const enReparacion = data.filter(c => c.estado_vehiculo === "En reparación").length;
const listos = data.filter(c => c.estado_vehiculo === "Listo para entrega").length;

document.getElementById("resumenPortal").innerHTML = `
<div class="resumen-card pendiente">🔴 Citas pendientes: ${pendientes}</div>
<div class="resumen-card">📅 Citas de hoy: ${citasHoy}</div>
<div class="resumen-card">🔧 En reparación: ${enReparacion}</div>
<div class="resumen-card">✅ Listos: ${listos}</div>
`;

const q=(document.getElementById("buscar").value||"").toLowerCase();const filtradas=data.filter(c=>`${c.folio||""} ${c.nombre} ${c.telefono} ${c.marca} ${c.modelo} ${c.placas}`.toLowerCase().includes(q));cont.innerHTML=filtradas.map(c=>`<div class="cita"><h3>${c.nombre}</h3><span class="badge">Folio: ${c.folio||"Sin folio"}</span><span class="badge">${c.estado_cita}</span><span class="badge">${c.estado_vehiculo}</span><p><b>Tel:</b> ${c.telefono}</p><p><b>Auto:</b> ${c.marca||""} ${c.modelo||""} ${c.anio||""} ${c.placas?" | Placas: "+c.placas:""}</p><p><b>Servicio:</b> ${c.servicio}</p><p><b>Fecha:</b> ${c.fecha} <b>Hora:</b> ${String(c.hora).slice(0,5)}</p><p><b>Cliente comentó:</b> ${c.comentarios||"Sin comentarios"}</p><p><b>Presupuesto:</b> $${c.presupuesto||0}</p>
<p><b>Entrega estimada:</b> ${c.fecha_entrega_estimada||"Sin definir"}</p>
<p><b>Avance visible:</b> ${c.avance_cliente||"Sin actualización."}</p><div class="acciones"><select onchange="actualizarCampo('${c.id}','estado_cita',this.value)">${opciones(["Pendiente","Confirmada","Cancelada"],c.estado_cita)}</select><select onchange="actualizarEstadoVehiculo('${c.id}',this.value)">${opciones(["Agendado","Recibido","En diagnóstico","Presupuesto enviado","En reparación","Listo para entrega","Entregado"],c.estado_vehiculo)}</select><button onclick="pedirPresupuesto('${c.id}')">Presupuesto</button>
<button onclick="pedirFechaEntrega('${c.id}')">Fecha entrega</button>
<button onclick="pedirAvance('${c.id}')">Actualizar avance</button><a class="btn whatsapp" target="_blank" href="https://wa.me/52${limpiarTelefono(c.telefono)}?text=${encodeURIComponent('Hola '+c.nombre+', te escribimos del taller. Tu folio es '+(c.folio||''))}">WhatsApp</a></div></div>`).join("")||"<p>No hay citas.</p>";}
function opciones(arr,actual){return arr.map(x=>`<option ${x===actual?"selected":""}>${x}</option>`).join("")}async function actualizarEstadoVehiculo(id,estado){await actualizarCampo(id,"estado_vehiculo",estado,false);let avance="";if(estado==="Recibido")avance="Tu vehículo ya fue recibido en el taller.";if(estado==="En diagnóstico")avance="Tu vehículo está en diagnóstico.";if(estado==="Presupuesto enviado")avance="El presupuesto ya fue generado. Puedes revisarlo aquí o por WhatsApp.";if(estado==="En reparación")avance="Tu vehículo está en reparación.";if(estado==="Listo para entrega")avance="Tu vehículo está listo para entrega.";if(estado==="Entregado")avance="Tu vehículo fue entregado. Gracias por tu confianza.";if(avance)await actualizarCampo(id,"avance_cliente",avance,false);cargarCitas();}async function actualizarCampo(id,campo,valor,recargar=true){const payload={};payload[campo]=valor;payload.fecha_actualizacion=new Date().toISOString();const{error}=await supabaseClient.from("citas").update(payload).eq("id",id);if(error){alert("No se pudo actualizar.");console.error(error);}if(recargar)cargarCitas();}async function pedirPresupuesto(id){const presupuesto=prompt("Ingresa presupuesto:");if(presupuesto===null)return;await actualizarCampo(id,"presupuesto",Number(presupuesto));}async function pedirAvance(id){const avance=prompt("Escribe el avance que verá el cliente:");if(avance===null)return;await actualizarCampo(id,"avance_cliente",avance);}async function cargarClientes(){const cont=document.getElementById("listaClientes");const{data,error}=await supabaseClient.from("clientes").select("*").order("created_at",{ascending:false});if(error){cont.innerHTML="<p>Error al cargar clientes.</p>";return;}cont.innerHTML=data.map(c=>`<div class="cliente"><h3>${c.nombre}</h3><p>${c.telefono}</p><a class="btn whatsapp" target="_blank" href="https://wa.me/52${limpiarTelefono(c.telefono)}">WhatsApp</a></div>`).join("");}async function cargarVehiculos(){const cont=document.getElementById("listaVehiculos");const{data,error}=await supabaseClient.from("vehiculos").select("*").order("created_at",{ascending:false});if(error){cont.innerHTML="<p>Error al cargar vehículos.</p>";return;}cont.innerHTML=data.map(v=>`<div class="vehiculo"><h3>${v.marca||""} ${v.modelo||""}</h3><p>Año: ${v.anio||""}</p><p>Placas: ${v.placas||""}</p></div>`).join("");}function limpiarTelefono(tel){return String(tel).replace(/\D/g,"")}
